### ISSUE TITLE
Provide step-by-step commits in Chapter 12.

### ISSUE THREAD

**Issue by reitowo** [PacktPublishing/Learn-LLVM-12#3]
Hi,

Thanks for the nice book you published. It will be much friendly and much more clear if you can provide step-by-step commit, not only a single diff file of the m88k backend implementation. Just like https://github.com/lowRISC/riscv-llvm, it provides step-by-step diff files. This will provide a timeline sequence about which part of backend should be implemented first, which helps backend beginners a lot!

**Comment by cnSchwarzer** [comment]
> Thanks for the feedback! That is a very good point. I did not realize this when writing.

Any plan for this? 👀

**Comment by reitowo** [comment]
@redstar I recently bought Learn LLVM 17 and find out you've split the m88k diff into 9 parts! Thank you!
